apiVersion: v1
kind: Service
metadata:
  name: '{{ branch }}-smtp'
  namespace: '{{ namespace }}'
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: '{{ app }}-{{ branch }}-{{ build }}'
  sessionAffinity: None
  type: ClusterIP